Putzen
IBFAIT/dokinator pull request #4
Opened 2016-11-09 12:00 UTC by casaper

2016-11-11 10:08 UTC, macrozone commented
ok, review done.

2016-11-11 10:08 UTC, macrozone requested changes

2016-11-11 10:08 UTC, macrozone commented on src/components/BotBubble.js
> +}
👍 
this looks similar to what we usually use for styles. We usually just use `styles` instead of `Styl`

2016-11-11 10:08 UTC, macrozone commented on src/components/BotPart.js
> +              bubbleText = (Array.isArray(bubbleText)) ? this.props.handleRandomBubble(bubbleText, bubbleIndex) : bubbleText;
as a rule of thumb 👍  you should generally never re-assign variables / function params. Can you come up with a solution that does not reasign `bubbleText`?

Also, handleRandomBubble looks odd. Does it operate on this.props.bot.texts  and just picks a random of it? Has it sideeffects (yes it has, as we will see below).

2016-11-11 10:08 UTC, macrozone commented on src/components/Icon.js
> +    maxWidth: (vals.icon.img.length+4) + 'px',
in react, a unitless int value on styles like width, minWidth, etc. are always pixels.

so you can just write `minWidth: vals.icon.img.length+4`

2016-11-11 10:08 UTC, macrozone commented on src/components/Icon.js
> +const Icon = ({ id }) => {
maybe `type` or `name` is the better property name here. `id` is somewhat reserved.

`<Icon type="fred" /> or <Icon name="fred" />`

2016-11-11 10:08 UTC, macrozone commented on src/components/Main.js
>    handleForwardTimeout({index, time = 2000}) {
maybe find a better name for this function?

it should describe what it does. Does it jump to the next step or so?

2016-11-11 10:08 UTC, macrozone commented on src/components/Main.js
> +      path: this.Conversation[this.state.path].user.answers[0].path
`this.Conversation[this.state.path].user.answers[0].path`
looks arbitrary. Does this function has something to to with user answers? why picking the first answer here? What is params?

2016-11-11 10:08 UTC, macrozone commented on src/components/Main.js
>      }, time, this, params);
why passing this and params to setTimeout?

2016-11-11 10:08 UTC, macrozone commented on src/components/Main.js
>    updatePathState(evt, {path, index = null}) {
what is index?

2016-11-11 10:08 UTC, macrozone commented on src/components/Main.js
>        stateAtPos: JSON.stringify(this.state),
why do you need to stringify state?

2016-11-11 10:08 UTC, macrozone commented on src/components/Main.js
>      /* ToDo: chrome complains about this enter detection beeing deprecated */
i think you neeed evt.which and map it to key codes (google it)

2016-11-11 10:08 UTC, macrozone commented on src/components/Main.js
> +      });
this again looks odd. Why need stringify?

2016-11-11 10:08 UTC, macrozone commented on src/components/Main.js
>    handleInputfieldEnter({evt, path, index, changeVal}) {
do we need path and index? what do these properties mean?

2016-11-11 10:08 UTC, macrozone commented on src/components/Main.js
>        templateVars[changeVal] = evt.target.value;
naming:

i think templateVars is not really descriptive. What is it exactly? I think it has something to do with the user. Some infos that you gain from the user. Think about it.

also, changeVal is a missnomer. The convention is usually: `object[key] =  value`. Or `object[property] = value`.

So maybe it should be something like `userData[property] = value`;

or maybe even:

```
const userData = {
 ....this.state.userData,
 ....newUserData
}
```

so `handleInputfieldEnter` would become something like `updateUserData(newUserData)`

which can be called with: 

```
updateUserData({
  name: "Hans Muster",
  email: "hans.muster@example.com"
});
```

i am not sure, but i think you do neither need "path" nor "index" because you got these infos already somewhere in the state.

2016-11-11 10:08 UTC, macrozone commented on src/components/Main.js
> +
this function has a side effect and returns something. That should be avoided.

also, I thought from the code that this.Conversation is static and will never change during runtime, but here it gets updated.

also, what is "bubbleText" ? I know its supposed to be an array, but from the name i think it is a string, but `_.sample(aString)` makes no sense to me.

Also, do you really need to pass `bubbleText`? don't you already have that info somewhere in this.Conversation?

2016-11-11 10:08 UTC, macrozone commented on src/components/Main.js
> +              conversation={this.Conversation}
does conversationLog contain all the infos to fully re-create the log? or does it need conversation data?

2016-11-11 10:08 UTC, macrozone commented on src/components/Main.js
> +            answers={user.answers}
are `user.answers` really the user's answers? I think it's more like "possible answers"

2016-11-11 10:08 UTC, macrozone commented on src/components/Main.js
> +            callbacks={callbacks}
avoid general names like this. What callbacks are these? do you need to pass all of them?

2016-11-11 10:08 UTC, macrozone commented on src/components/PastPart.js
> +  const stateAtPos = JSON.parse(step.stateAtPos); // get the striggified state from the past
why is stateAtPos stringified in the first place?

2016-11-11 10:08 UTC, macrozone commented on src/components/PastPart.js
> +    <div key={'conv_'+stepIndex} >
you don't need to add a key if you return just one react-element

2016-11-11 10:08 UTC, macrozone commented on src/components/PastPart.js
> +        key={'client_'+stepIndex}
same same, key is not needed

2016-11-11 10:08 UTC, macrozone commented on src/components/PastPart.js
> +        stepIndex={stepIndex}
does it need the index?

2016-11-11 10:08 UTC, macrozone commented on src/components/PastPart.js
> +        index={step.index}
what is the difference to stepIndex?

2016-11-11 10:08 UTC, macrozone commented on src/components/PastPart.js
> +        stateAtPos={stateAtPos}
you already "consumed" stateAtPos above. Does UserAnswerPast need that as well?

2016-11-11 10:08 UTC, macrozone commented on src/components/UserAnswerPart.js
> +const Style = {
be consequent with your naming

2016-11-11 10:08 UTC, macrozone commented on src/components/UserAnswerPart.js
> +        handleForwardTimeout({answerIndex: 0});
this looks misplaced here. The other cases return a react element and this here does something.

2016-11-11 10:08 UTC, macrozone commented on src/components/UserAnswerPast.js
> +  if(answer.length == 1 && answer[0].type == 'forward') {
why is answer[0] special?

2016-11-11 10:08 UTC, macrozone commented on src/components/UserButton.js
> +const typeStyl = {
inconsequent naming

2016-11-11 10:08 UTC, macrozone commented on src/components/UserButton.js
> +  Style = (type === 'past') ? {...Style, ...typeStyl.past} : Style;
in general, try to avoid using `let`

2016-11-11 10:08 UTC, macrozone commented on src/components/UserButton.js
> +  let dynProps = (type === null) ? {onClick: e => {updatePathState(e, {path, index})}} : {};
1.) use always `const` unless you have a really good reason to not use `const`
2.) does `updatePathState` really need the whole event? 
3.) what is the case `type === null` ? when does this happen?
4.) dynProps is not really a good name. It just contains a onClick-function. So just pass `onClick` on the div below.

2016-11-11 10:08 UTC, macrozone commented on src/components/UserInputField.js
> +      onKeyPress={evt => {handleInputfieldEnter({evt, path, index, changeVal})}}
what does `handleInputfieldEnter` need from the event? does it need the whole event? Does it need to fire on every kepress?

2016-11-11 10:08 UTC, macrozone commented on src/styles/genStyl.js
> +  },
These styles look very specific and not generic.

In general, prefer "good" components that can be used more generally, like a `<Bubble />` or something that have these styles

2016-11-12 12:49 UTC, casaper commented on src/components/Main.js
>      /* ToDo: chrome complains about this enter detection beeing deprecated */
but `event.key` as well as `event.which` are all deprecated, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which). But for the quick I only found `evt.code` that doesn't seem to be working for some unknown reason. So what do you suggest?

2016-11-17 10:37 UTC, closed without merging